### ISSUE TITLE
Exception in the TCP server

### ISSUE THREAD

**Issue by tklecka** [OpenDroneAT/OpenDrone-FlightController#100]
**Describe the bug**
Got an Exception in the TCP server

**To Reproduce**
Dont know

**Expected behavior**
Exception 

**Linux (please complete the following information):**
 - Version dev branche
 - FC Version -

**Additional context**
![shorty](https://user-images.githubusercontent.com/19475513/51618815-3f73fa00-1f2f-11e9-9d14-a3e96aa89862.PNG)

**Comment by MarkusKurzmann** [comment]
@tklecka: Please write a sufficient description of the bug, otherwise i cant fix this.

**Comment by tklecka** [comment]
@MarkusKurzmann i dont know why this error happens 🤷‍♂️
