### ISSUE TITLE
FEATURE REQUEST - Check motor number

### ISSUE THREAD

**Issue by MarkusKurzmann** [OpenDroneAT/OpenDrone-FlightController#111]
**Is your feature request related to a problem? Please describe.**
It would be nice if there was a button for running a kind of motor test, which lets the different motors spin in an ascending numeric order so you know what motor which one is

**Describe the solution you'd like**
read above

**Describe alternatives you've considered**
You press on a button and the motors spin in an ascending numeric order.

**Additional context**
No

**Comment by michaelhitzker** [comment]
@tbrych do it!
